### ISSUE TITLE
no config_inc.php created

### ISSUE THREAD

**Issue by tamis-laan** [xlrl/docker-mantisbt#14]
I have followed the installation instructions as provided in the README. The only thing I changed is the volume specification in the docker compose file:

```yml
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always

  mantisbt:
    image: xlrl/mantisbt:latest
    ports:
      - 8989:80
    links:
      - mysql
    volumes:
      - ./docker/mantisbt/config:/var/www/html/config             <-- changed
      - ./docker/mantisbt/custom:/var/www/html/custom         <-- changed
    restart: always
```

After going to `localhost:8989` and filling in the required install information for mantis, all the checks are passed as GOOD and highlighted in green. However inspecting `./docker/mantisbt/config` does not show any file named `config_inc.php`. Furthermore pressing the `back to Administration` button sends me to a page with the following error:

```
APPLICATION ERROR #2900

For security reasons MantisBT will not operate when $g_crypto_master_salt is not specified correctly in config_inc.php or is shorter than 16 characters long.

Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.
```

I'm not sure where I'm going wrong but I'm guessing `config_inc.php` is not generated? I can't judge if this is a bug or I'm doing to something wrong.
