### ISSUE TITLE
Missing database file?

### ISSUE THREAD

**Issue by jxpsert** [xlrl/docker-mantisbt#23]
Hi there! Trying to set up using the readme as a guide. I'm getting this error once I click the 'Install' button after filling in my settings:

``[Fri Dec 01 13:56:36.188601 2023] [php:notice] [pid 18] [client 172.25.0.1:40270] No such file or directory\n/var/www/html/vendor/adodb/adodb-php/drivers/adodb-mysqli.inc.php: 124: - - - - mysqli_real_connect( <Object><mysqli> (  ), <string>'localhost', <string>'redacted', <string>'redacted', <string>'', <integer>3306, <string>'', <integer>0 )\n/var/www/html/vendor/adodb/adodb-php/adodb.inc.php: 695: ADODB_mysqli - -> - _connect( <string>'localhost', <string>'redacted', <string>'redacted', <string>'' )\n/var/www/html/admin/install.php: 423: ADOConnection - -> - Connect( <string>'localhost', <string>'redacted', <string>'redacted' )\n, referer: https://bt.ptdk.nl/admin/install.php``

I've changed personal details to 'redacted'.

I'm using the docker-compose that was provided in the readme:
```
version: '2'
services:
  mantisbt:
    image: xlrl/mantisbt:latest
    ports:
      - "8989:80"
    links:
      - mysql
    volumes:
      - ./config:/var/www/html/config
      - ./custom:/var/www/html/custom
    restart: always

  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
```
