### ISSUE TITLE
Error while installing: Does administrative user have access to the database? ( No such file or directory )

### ISSUE THREAD

**Issue by mk48** [xlrl/docker-mantisbt#4]
Below is my docker compose file
```
mantisbt:
  image: xlrl/mantisbt:latest
  ports:
    - "8989:80"
  links:
    - mysql
  volumes:
    - C:/docker/mantisbt/config:/var/lib/www/html/config
    - C:/docker/mantisbt/custom:/var/lib/www/html/custom
  restart: always

mysql:
  image: mariadb:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=bugtracker
    - MYSQL_USER=mantisbt
    - MYSQL_PASSWORD=mantisbt
  volumes:
    - C:/docker/mantisbt/mysql:/var/lib/mysql
  restart: always
```
I am able to open http://localhost:8989/admin/install.php page

![image](https://user-images.githubusercontent.com/3082469/53551408-4362ef80-3b5f-11e9-907a-1aa246c91e97.png)

Getting that error when I click "Install/Upgrade Database" button 

I am getting below error in **docker-compose up** command window, is it the reason?

![image](https://user-images.githubusercontent.com/3082469/53551658-c6844580-3b5f-11e9-83a7-cda9454d68e4.png)
